# Generated by Django 3.1.6 on 2021-02-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210221_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='product',
            field=models.ManyToManyField(related_name='watchlist_products', to='auctions.AuctionList'),
        ),
    ]
